type Hotel {
    id: ID!
    name: String!
    location: String!
    rating: String!
    isAvailable: Boolean
    imageUrl: String
    pricePerNight: Int!
}

input HotelInput {
    id: ID!
}


type Guest {
    id: ID!
    firstName: String!
    gender: String!
    reservations: [Reservation]
}

type Review {
    id: ID!
    rating: String!
    comment: String!
    hotel: Hotel!
}

type Reservation {
    id: ID!
    hotelName: String!
    location: String!
    checkInDate: String!
    checkOutDate: String!
}

type Query {
    getHotelById(id: ID!): Hotel
    getAllHotels: [Hotel]

    getGuestById(id: ID!): Guest
    getAllGuests: [Guest]

    getReviewById(id: ID!): Review
    getAllReviews: [Review]

    getReservationById(id: ID!): Reservation
    getAllReservations: [Reservation]
}


type Mutation {
    addHotel(
        name: String!, 
        location: String!, 
        rating: String!, 
        isAvailable: Boolean!, 
        pricePerNight: Int!,
        imageUrl: String
    ): Hotel

    addGuest(
        firstName: String!, 
        gender: String!
    ): Guest

    addReview(
        rating: String!, 
        comment: String!, 
        hotel: HotelInput!
    ): Review

    addReservation(
        hotelName: String!
        location: String!
        checkInDate: String!
        checkOutDate: String!
    ): Reservation

}
