type Hotel {
    id: ID!
    name: String!
    location: String!
    rating: Int!
    contactNumber: String!
    rooms: [Room]
    reviews: [Review]
    reservations: [Reservation]
}

type Room {
    id: ID!
    roomNumber: String!
    type: String!
    price: Float!
    isAvailable: Boolean!
    hotel: Hotel!
}

type Guest {
    id: ID!
    firstName: String!
    lastName: String!
    email: String!
    phoneNumber: String!
    reservations: [Reservation]
    reviews: [Review]
}

type Review {
    id: ID!
    rating: Int!
    comment: String!
    guest: Guest!
    hotel: Hotel!
}

type Reservation {
    id: ID!
    guest: Guest!
    hotel: Hotel!
    checkInDate: String!
    checkOutDate: String!
    room: Room!
}

type Query {
    getHotelById(id: ID!): Hotel
    getAllHotels: [Hotel]

    getRoomById(id: ID!): Room
    getAllRooms: [Room]

    getGuestById(id: ID!): Guest
    getAllGuests: [Guest]

    getReviewById(id: ID!): Review
    getAllReviews: [Review]

    getReservationById(id: ID!): Reservation
    getAllReservations: [Reservation]
}

type Mutation {
    addHotel(name: String!, location: String!, rating: Int!, contactNumber: String!): Hotel
    addRoom(roomNumber: String!, type: String!, price: Float!, isAvailable: Boolean!, hotelId: ID!): Room
    addGuest(firstName: String!, lastName: String!, email: String!, phoneNumber: String!): Guest
    addReview(rating: Int!, comment: String!, guestId: ID!, hotelId: ID!): Review
    addReservation(guestId: ID!, hotelId: ID!, checkInDate: String!, checkOutDate: String!, roomId: ID!): Reservation
}
