spring.application.name=hotel-transylvania

# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/hotel_transylvania
spring.datasource.username=root
spring.datasource.password=2344
server.port=8081

# MySQL server is local

# Hibernate Properties
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
