# Application Info
spring.application.name=hotel-reservation
server.port=8082

# SQLite Database Configuration
#spring.datasource.url=jdbc:sqlite:hotel_transylvania?cache=shared
#spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Hibernate & SQL Behavior
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.sql.init.mode=always

driverClassName=org.sqlite.JDBC
url=jdbc:sqlite:hotel_transylvania.db
username=sa 
password=sa
hibernate.show_sql=true


# GraphiQL Interface (GraphQL Playground)
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
